import time
from fastapi import APIRouter, HTTPException, UploadFile, File, Request
from pydantic import BaseModel, Field
import httpx
import os
import logging
from services.voice_utils import transcribe_audio_bytes, synthesize_speech_bytes
import base64

logger = logging.getLogger("backend.orchestrator.gateway")

router = APIRouter(prefix="/api/v1")

# Core AI URL definition (KMS RAG Engine runs on port 8001)
CORE_AI_URL = os.getenv("CORE_AI_URL", "http://localhost:8001/api/v1/search")


# ==========================================
# Pydantic Schemas
# ==========================================
class QueryRequest(BaseModel):
    query: str = Field(
        ...,
        min_length=1,
        max_length=2000,
        description="Search query string for RAG",
        examples=["Làm thế nào để kích hoạt phanh khẩn cấp ADAS?"],
    )

class CitationPayload(BaseModel):
    document_id: str = "doc_unk"
    document_name: str = "Unspecified Document"
    section: str = "General"
    page: int = 1
    matched_text: str = ""

class QueryResponse(BaseModel):
    query: str
    answer: str
    citations: list[CitationPayload] = []
    status: str = "success"

class LatencyMetrics(BaseModel):
    stt_ms: int = 0
    core_ai_ms: int = 0
    tts_ms: int = 0
    total_ms: int = 0
    
class VoiceQueryResponse(BaseModel):
    transcript: str
    answer: str
    audio_base64: str | None = None
    citations: list[CitationPayload] = []
    latency: LatencyMetrics

# ==========================================
# Router Endpoints
# ==========================================
@router.get("/health")
async def gateway_health():
    return {"status": "ok", "service": "backend-orchestrator-gateway"}


@router.post("/copilot/query", response_model=QueryResponse)
async def route_text_query(payload: QueryRequest, request: Request):
    logger.info(f"[Gateway] Forwarding text query to Core AI: '{payload.query}'")
    try:
        client: httpx.AsyncClient = request.app.state.http_client
        # Forward the text search query to the KMS Core AI microservice using shared connection pool
        response = await client.post(CORE_AI_URL, json={"query": payload.query})
        if response.status_code != 200:
            logger.error(
                f"[Gateway] Core AI upstream error: status={response.status_code}, body={response.text}"
            )
            raise HTTPException(
                status_code=response.status_code,
                detail=f"Core AI returned an error: {response.text}",
            )

        data = response.json()
        return QueryResponse(
            query=data.get("query", payload.query),
            answer=data.get("answer", "No response generated by Core AI."),
            citations=data.get("citations", []),
            status=data.get("status", "success"),
        )

    # --- START MODIFICATION ---
    # CI fix: use logger.exception for G201 (ruff)
    except httpx.TimeoutException as e:
        logger.exception(f"[Gateway] Timeout connecting to Core AI: {e}")
        raise HTTPException(
            status_code=504,
            detail="Gateway Timeout: KMS Core AI service took too long to respond.",
        )

    except httpx.RequestError as e:
        logger.exception(f"[Gateway] Request failed connecting to Core AI: {e}")
        raise HTTPException(
            status_code=502,
            detail="Bad Gateway: KMS Core AI service is currently unreachable.",
        )
    # --- END MODIFICATION ---


@router.post("/copilot/voice-query", response_model=VoiceQueryResponse)
async def route_voice_query(file: UploadFile, request: Request):
    total_start = time.perf_counter()
    logger.info(f"[Gateway] Received voice query file: name={file.filename}")

    audio_content = await file.read()
    if not audio_content:
        raise HTTPException(
            status_code=400, detail="Uploaded audio file is empty."
        )
    
    transcript, stt_ms = await transcribe_audio_bytes(audio_content, filename=file.filename or "input_voice.mp3")
    if not transcript:
        raise HTTPException(
            status_code=500, detail="Failed to transcribe audio query."
        )
    
    core_ai_start = time.perf_counter()

    try:
        client: httpx.AsyncClient = request.app.state.http_client
        response = await client.post(CORE_AI_URL, json={"query": transcript})
        if response.status_code != 200:
            logger.error(
                f"[Gateway] Core AI upstream error in voice flow: status={response.status_code}"
            )
            raise HTTPException(
                status_code=500,
                detail="Core AI failed executing search."
            )

        data = response.json()

        core_ai_ms = int((time.perf_counter() - core_ai_start) * 1000)
        audio_bytes, tts_ms = await synthesize_speech_bytes(data.get("answer", ""))
        audio_b64 = base64.b64encode(audio_bytes).decode("utf-8") if audio_bytes else None
        total_ms = int((time.perf_counter() - total_start) * 1000)

        return VoiceQueryResponse(
            transcript=transcript,
            answer=data.get("answer", "No response generated by Core AI."),
            audio_base64=audio_b64,
            citations=data.get("citations", []),
            latency=LatencyMetrics(
                stt_ms=stt_ms,
                core_ai_ms=core_ai_ms,
                tts_ms=tts_ms,
                total_ms=total_ms,
            ),
        )

    # --- START MODIFICATION ---
    # CI fix: use logger.exception for G201 (ruff)
    except httpx.TimeoutException as e:
        logger.exception(f"[Gateway] Voice flow timeout: {e}")
        raise HTTPException(
            status_code=504,
            detail="Gateway Timeout: KMS Core AI service took too long to respond.",
        )

    except httpx.RequestError as e:
        logger.exception(f"[Gateway] Voice flow connection error: {e}")
        raise HTTPException(
            status_code=502,
            detail="Bad Gateway: KMS Core AI service is currently unreachable.",
        )
    # --- END MODIFICATION ---
    

    
@router.post("/voice/transcribe")
async def transcribe_audio(file: UploadFile = File(...)):
    # Mock Speech-to-Text translation service
    return {"transcript": "Làm thế nào kích hoạt phanh khẩn cấp ADAS?"}


@router.post("/voice/synthesize")
async def synthesize_speech(text: str):
    # Mock Text-to-Speech synthesis service
    return {"audio_url": "/static/audio/response_123.mp3"}
